<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Thu, 11 Sep 2008 10:36:46 +0700
 */
$conf['title'] = 'KnowledgeBase';
$conf['lang'] = 'en';
$conf['useacl'] = 1;
$conf['superuser'] = 'msolliday';
